version: '3'
services:

  # backend:
  #   build: ./backend
  #   container_name: backend-dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend/src:/app
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  
  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start -- --host 0.0.0.0
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: my-nginx-auth
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped
    depends_on:
      - frontend
    networks:
      - app-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
      
networks:
  app-network:
    driver: bridge
